### ISSUE TITLE
base-cluster: integrate tetragon

### ISSUE THREAD

**Issue by cwrau** [teutonet/teutonet-helm-charts#1046]
- [x] install tetragon
- [x] connect it to prometheus
- [x] add grafana dashboard (skipped for now)
- [ ] allow configuration for a "high-security" mode, locking down as much as possible
- [x] configure image registry
- [x] allow images in trusted_registries
- [x] try to not use the operator

**Comment by tasches** [comment]
There is a helm chart for tetragon available. We can try a protype installation of it
[tetragon-helmchart](https://artifacthub.io/packages/helm/cilium/tetragon)

**Comment by marvinWolff** [comment]
After searching for a dashboard and not finding a good one i will leave the dashboard out for now.

**Comment by marvinWolff** [comment]
Tetragon is implemented. After much testing we decided not to include default policies, as these are highly individiual and have a risk of locking down the cluster from all access.
