### ISSUE TITLE
[base-cluster] add new dashboards to grafana

### ISSUE THREAD

**Issue by cwrau** [teutonet/teutonet-helm-charts#652]
The dashboards 15758 and 15826 add nice namespace overviews, we should decide which one, or both, we want to keep.

**Comment by marvinWolff** [comment]
I think its a bit hard to compare without testing them, so i will add them both in the mr and remove one if one fits our needs.

**Comment by marvinWolff** [comment]
I've removed 15826, i see no value in it that is not given in 15758. Plus, the queries do not work.

In 15758 all queries work, with exception of the pvc metrics. 

We can either fix that and maintain our own copy or ignore it. There is enough data besides the volumes that it's interesting.

**Comment by tasches** [comment]
I like the dashboard and I can confirm, that the PR is working. In my opinion we do not need the metrics about the PVCs and maintaining a copy of the dashboard isn"t worth it.
