### ISSUE TITLE
upgrade all HelmRelease to v2beta2

### ISSUE THREAD

**Issue by tasches** [teutonet/teutonet-helm-charts#740]
flux upgraded their crds in v2.2.0 to v2beta2. We should update our HelmReleases

**Comment by cwrau** [comment]
And during this we should set `.spec.driftDetection.mode=enabled` for each and every HelmRelease 🙄

See https://github.com/fluxcd/helm-controller/issues/643

**Comment by tasches** [comment]
PR t8s-cluster: #774 
PR base-cluster: #773

**Comment by tasches** [comment]
@cwrau, @marvinWolff 
please review the changes and test them by yourselfes.

**Comment by tasches** [comment]
base-cluster mr needs to merged as well
