### ISSUE TITLE
[base-cluster] trivy node-collector in pending state

### ISSUE THREAD

**Issue by marvinWolff** [teutonet/teutonet-helm-charts#745]
At the moment the trivy node-collector can not be scheduled.  

This should be fixed.

**Comment by tasches** [comment]
podAffinity and kyverno policies prevents it from being scheduled.

I tried a fix which needs to be validated. In the trivy helmrelease add
```yaml
    nodeCollector:
      useNodeSelector: false

```
after that the pod can be scheduled. However, the pod does not have any logs and I am not sure if it actually works

**Comment by jpkraemer-mg** [comment]
We've had the same problem with our installation of Trivy. For us, the reason was Node Taints, might want to check whether that's the case for you, which for the TrivyOperator can be fixed with trivyOperator.scanJobTolerations
